export enum ColorEnum {
    white = 'has-text-white',
    black = 'has-text-black',
    light = 'has-text-light',
    dark = 'has-text-dark',
    primary = 'has-text-primary',
    info = 'has-text-info',
    link = 'has-text-link',
    success = 'has-text-success',
    warning = 'has-text-warning',
    danger = 'has-text-danger',
    blackBis = 'has-text-black-bis',
    blackTer = 'has-text-black-ter',
    greyDarker = 'has-text-grey-darker',
    greyDark = 'has-text-grey-dark',
    grey = 'has-text-grey',
    greyLight = 'has-text-grey-light',
    greyLighter = 'has-text-grey-lighter',
    whiteTer = 'has-text-white-ter',
    whiteBis = 'has-text-white-bis'
}